spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kdd
    username: kdd
    password: kdd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  google:
    redirect-uri: ${GOOGLE_REDIRECT_URI}
  cors:
    allowed-origins: http://localhost:3000
    secure-cookie: false
