-- Baseline schema for KDD API.
-- Mirrors the Hibernate-generated schema as of 2026-04-28 with stabilised
-- constraint names. Existing deployments are baselined past this version
-- (see spring.flyway.baseline-version) so it only runs on fresh databases.
-- Enum CHECK constraints are introduced in V2.

CREATE TABLE users (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                 VARCHAR(255) NOT NULL,
    name                  VARCHAR(100) NOT NULL,
    role                  VARCHAR(20)  NOT NULL,
    user_type             VARCHAR(20)  NOT NULL,
    is_active             BOOLEAN      NOT NULL,
    is_profile_completed  BOOLEAN      NOT NULL,
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);
CREATE INDEX idx_user_user_type ON users (user_type);

CREATE TABLE document_categories (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    parent_id   BIGINT,
    depth       INTEGER      NOT NULL,
    sort_order  INTEGER      NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_document_categories_parent
        FOREIGN KEY (parent_id) REFERENCES document_categories(id)
);
CREATE INDEX idx_doc_category_parent      ON document_categories (parent_id);
CREATE INDEX idx_doc_category_parent_sort ON document_categories (parent_id, sort_order);

CREATE TABLE documents (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(255) NOT NULL,
    content            TEXT,
    summary            TEXT,
    category_id        BIGINT       NOT NULL,
    source             VARCHAR(20)  NOT NULL,
    original_url       VARCHAR(1000),
    author             VARCHAR(100),
    published_at       TIMESTAMP(6),
    original_filename  VARCHAR(255),
    storage_key        VARCHAR(500),
    mime_type          VARCHAR(100),
    file_size          BIGINT,
    view_count         INTEGER      NOT NULL,
    is_notice          BOOLEAN      NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    deleted_at         TIMESTAMP(6),
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_documents_category
        FOREIGN KEY (category_id) REFERENCES document_categories(id)
);
CREATE INDEX idx_doc_category     ON documents (category_id);
CREATE INDEX idx_doc_title        ON documents (title);
CREATE INDEX idx_doc_status       ON documents (status);
CREATE INDEX idx_doc_published_at ON documents (published_at);

CREATE TABLE document_chunks (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id   BIGINT       NOT NULL,
    content       TEXT         NOT NULL,
    chunk_index   INTEGER      NOT NULL,
    page          INTEGER,
    section_path  VARCHAR(500),
    has_table     BOOLEAN      NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_chunk_doc_index UNIQUE (document_id, chunk_index),
    CONSTRAINT fk_document_chunks_document
        FOREIGN KEY (document_id) REFERENCES documents(id)
);
CREATE INDEX idx_chunk_document ON document_chunks (document_id);

CREATE TABLE staff_profiles (
    user_id          BIGINT       PRIMARY KEY,
    department       VARCHAR(30)  NOT NULL,
    job_description  TEXT,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_staff_profiles_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE student_profiles (
    user_id          BIGINT       PRIMARY KEY,
    student_id       VARCHAR(30)  NOT NULL,
    department       VARCHAR(20)  NOT NULL,
    grade            SMALLINT     NOT NULL,
    admission_year   SMALLINT     NOT NULL,
    academic_status  VARCHAR(20)  NOT NULL,
    additional_info  TEXT,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_student_profiles_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_student_profile_student_id ON student_profiles (student_id);

CREATE TABLE auth_sessions (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    refresh_token_hash  VARCHAR(255) NOT NULL,
    expires_at          TIMESTAMP(6) NOT NULL,
    revoked_at          TIMESTAMP(6),
    last_used_at        TIMESTAMP(6),
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_auth_sessions_refresh_token_hash UNIQUE (refresh_token_hash),
    CONSTRAINT fk_auth_sessions_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_auth_session_user_id    ON auth_sessions (user_id);
CREATE INDEX idx_auth_session_expires_at ON auth_sessions (expires_at);

CREATE TABLE chat_sessions (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    title        VARCHAR(100) NOT NULL,
    source_type  VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_chat_sessions_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_chat_session_user_id    ON chat_sessions (user_id);
CREATE INDEX idx_chat_session_title      ON chat_sessions (title);
CREATE INDEX idx_chat_session_created_at ON chat_sessions (created_at);

CREATE TABLE chat_messages (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        BIGINT       NOT NULL,
    role              VARCHAR(20)  NOT NULL,
    content           TEXT         NOT NULL,
    confidence_level  VARCHAR(20),
    created_at        TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_chat_messages_session
        FOREIGN KEY (session_id) REFERENCES chat_sessions(id)
);
CREATE INDEX idx_chat_message_session_id ON chat_messages (session_id);
CREATE INDEX idx_chat_message_created_at ON chat_messages (created_at);

CREATE TABLE chat_message_sources (
    id                 BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id         BIGINT  NOT NULL,
    document_id        BIGINT  NOT NULL,
    document_chunk_id  BIGINT  NOT NULL,
    chunk_text         TEXT,
    page               INTEGER,
    CONSTRAINT uk_message_chunk UNIQUE (message_id, document_chunk_id),
    CONSTRAINT fk_chat_message_sources_message
        FOREIGN KEY (message_id)        REFERENCES chat_messages(id),
    CONSTRAINT fk_chat_message_sources_document
        FOREIGN KEY (document_id)       REFERENCES documents(id),
    CONSTRAINT fk_chat_message_sources_chunk
        FOREIGN KEY (document_chunk_id) REFERENCES document_chunks(id)
);
CREATE INDEX idx_chat_msg_src_message_id  ON chat_message_sources (message_id);
CREATE INDEX idx_chat_msg_src_document_id ON chat_message_sources (document_id);
CREATE INDEX idx_chat_msg_src_chunk_id    ON chat_message_sources (document_chunk_id);
