-- 1. FAQ 테이블 신설
-- enum_faq_category와 정렬되는 소문자 CHECK 제약 (Faq 모듈 PR1)
CREATE TABLE faqs (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question    TEXT         NOT NULL,
    answer      TEXT         NOT NULL,
    category    VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT faqs_category_check
        CHECK (category IN (
            'academic', 'graduation', 'enrollment_status', 'scholarship',
            'registration', 'curriculum', 'career', 'event', 'other'
        ))
);
CREATE INDEX idx_faq_category ON faqs (category);

-- 2. documents.is_notice 컬럼 제거
-- ERD 초기 설계 단계에서 공지/일반 구분용 placeholder로 추가했으나 현 요구사항에 매칭 기능이 없어
-- 코드 어디에서도 읽거나 쓰지 않는 상태(모든 row가 false 고정). 향후 공지 기능이 들어올 때 다시 추가.
ALTER TABLE documents DROP COLUMN is_notice;
