-- 채팅 횟수 제한 기능 추가
-- 1) users 테이블에 일일 채팅 한도 컬럼 추가 (기본 20회)
-- 2) 사용자별 일별 채팅 사용량 누적 테이블 신설 (자정 KST 리셋은 새 날짜 row가 0부터 시작하는 구조로 자동 처리)
-- 3) 전역 애플리케이션 설정 KV 테이블 신설 — 신규 가입자 default 한도를 코드 상수 대신 DB에 두어 재배포 없이 운영 중 조정
--
-- ALTER TABLE은 ACCESS EXCLUSIVE LOCK을 요구하므로 운영 long-running 쿼리와의 lock 큐 누적 방지 (V3 패턴과 동일)
SET LOCAL lock_timeout = '5s';

-- 1. users.daily_chat_limit
ALTER TABLE users
    ADD COLUMN daily_chat_limit INTEGER NOT NULL DEFAULT 20;
ALTER TABLE users
    ADD CONSTRAINT users_daily_chat_limit_check CHECK (daily_chat_limit >= 0);

-- 2. user_chat_usage
-- (user_id, usage_date) UNIQUE 제약이 PostgreSQL에서 동일 컬럼 조합의 인덱스를 자동 생성하므로
-- 별도의 CREATE INDEX는 두지 않는다. 사용자 hard delete를 막아 사용량 row의 고아화를 방지하기 위해
-- FK는 ON DELETE RESTRICT를 명시한다 (애플리케이션에서 명시적 정리 패턴과 일관).
CREATE TABLE user_chat_usage (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    usage_date   DATE         NOT NULL,
    chat_count   INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_chat_usage_user_date UNIQUE (user_id, usage_date),
    CONSTRAINT user_chat_usage_count_check CHECK (chat_count >= 0),
    CONSTRAINT fk_user_chat_usage_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);

-- 3. app_settings (전역 KV 설정)
CREATE TABLE app_settings (
    key_name     VARCHAR(100) NOT NULL PRIMARY KEY,
    value        VARCHAR(500) NOT NULL,
    description  VARCHAR(500),
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL
);

-- 4. 신규 가입자 default chat limit 초기값 (20회/일)
INSERT INTO app_settings (key_name, value, description, created_at, updated_at)
VALUES ('default_chat_limit', '20', '신규 가입자에게 적용되는 일일 채팅 한도',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
