-- ACCESS EXCLUSIVE LOCK이 필요한 CREATE TABLE 자체는 빠르지만, 운영 트래픽이 동일 schema
-- (특히 faqs 테이블)에 long-running 쿼리를 잡고 있을 경우 마이그레이션이 lock 큐에 갇혀 connection
-- pool을 고갈시킬 수 있다. V3와 같은 패턴으로 5초 안에 락을 획득하지 못하면 실패 후 롤백한다.
SET LOCAL lock_timeout = '5s';

-- FAQ 후보 테이블 신설
-- BE 스케줄러가 AI 서버 POST /api/faq/analyze 응답(인기 질문 TOP 5)을 받아 후보로 등록하고,
-- 관리자가 카테고리를 지정한 뒤 승인 시 faqs 테이블로 변환된다 (요구사항 4-(3)-1).
-- category는 AI가 분류한 값이 들어오나 nullable로 두어 분류 실패 케이스와 관리자 재지정을 허용한다.
CREATE TABLE faq_candidates (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question     TEXT         NOT NULL,
    draft_answer TEXT         NOT NULL,
    category     VARCHAR(20),
    frequency    INTEGER      NOT NULL DEFAULT 0,
    status       VARCHAR(20)  NOT NULL,
    approved_at  TIMESTAMP(6),
    rejected_at  TIMESTAMP(6),
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT faq_candidates_status_check
        CHECK (status IN ('pending', 'approved', 'rejected')),
    -- faqs 테이블과 동일한 enum 집합. nullable이지만 값이 있으면 9개 중 하나여야 한다.
    CONSTRAINT faq_candidates_category_check
        CHECK (category IS NULL OR category IN (
            'academic', 'graduation', 'enrollment_status', 'scholarship',
            'registration', 'curriculum', 'career', 'event', 'other'
        )),
    CONSTRAINT faq_candidates_frequency_check
        CHECK (frequency >= 0)
);

-- 관리자 목록 조회는 status 필터(PENDING만) + 최신순 정렬을 빈번히 사용하므로 복합 인덱스.
CREATE INDEX idx_faq_candidate_status_created
    ON faq_candidates (status, created_at DESC);
