-- ACCESS EXCLUSIVE LOCK이 필요한 CREATE TABLE 자체는 빠르지만, 운영 트래픽이 동일 schema
-- (특히 faqs 테이블)에 long-running 쿼리를 잡고 있을 경우 마이그레이션이 lock 큐에 갇혀 connection
-- pool을 고갈시킬 수 있다. V3와 같은 패턴으로 5초 안에 락을 획득하지 못하면 실패 후 롤백한다.
SET LOCAL lock_timeout = '5s';

-- FAQ 후보 테이블 신설 — [BE] ERD (8ca103a1) FAQCandidate 정의를 그대로 따른다.
-- BE 스케줄러가 AI 서버 POST /api/faq/analyze 응답(인기 질문 TOP 5)을 받아 후보로 등록하고,
-- 관리자가 카테고리를 지정한 뒤 승인 시 faqs 테이블로 변환되며 faq_id가 채워진다 (요구사항 4-(3)-1).
-- frequency는 AI 응답에 포함되지만 ERD에 컬럼이 없으므로 저장하지 않는다.
CREATE TABLE faq_candidates (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question      TEXT         NOT NULL,
    answer_draft  TEXT,
    category      VARCHAR(20),
    status        VARCHAR(20)  NOT NULL DEFAULT 'pending',
    faq_id        BIGINT,
    approved_at   TIMESTAMP(6),
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT faq_candidates_status_check
        CHECK (status IN ('pending', 'approved', 'rejected')),
    -- faqs 테이블과 동일한 enum 집합. nullable이지만 값이 있으면 9개 중 하나여야 한다.
    CONSTRAINT faq_candidates_category_check
        CHECK (category IS NULL OR category IN (
            'academic', 'graduation', 'enrollment_status', 'scholarship',
            'registration', 'curriculum', 'career', 'event', 'other'
        )),
    CONSTRAINT fk_faq_candidates_faq
        FOREIGN KEY (faq_id) REFERENCES faqs(id) ON DELETE SET NULL
);

-- ERD에 명시된 단일 인덱스 3개 그대로 — 관리자 목록 조회(status='pending' 필터), 카테고리별 조회,
-- 승인된 후보 → FAQ 역추적 용도.
CREATE INDEX idx_faq_candidate_status   ON faq_candidates (status);
CREATE INDEX idx_faq_candidate_category ON faq_candidates (category);
CREATE INDEX idx_faq_candidate_faq_id   ON faq_candidates (faq_id);
