-- ACCESS EXCLUSIVE LOCK이 필요한 CREATE TABLE 자체는 빠르지만, V3/V5와 같은 패턴으로
-- 운영 트래픽이 documents 테이블에 long-running 쿼리를 잡고 있을 가능성에 대비해 5초 안에 락 획득 실패 시 롤백.
SET LOCAL lock_timeout = '5s';

-- 인기 문서 점수 산정용 7일 윈도우 view tracking 테이블.
-- 노션 §"인기 문서 조회"의 "결정 논의사항: 문서 상세 진입 = 조회 수 증가?" 항목을 다음 정책으로 확정:
--   • 인증된 사용자가 문서 상세 조회(GET /documents/{documentId}) 호출할 때마다 row 1개 insert
--   • 출처 링크 클릭도 동일 엔드포인트를 거치므로 자동 카운트 (별도 클릭 추적 테이블/엔드포인트 불요)
--   • 인기 점수는 7일 윈도우 COUNT DISTINCT user_id — 한 사용자가 100번 진입해도 1로 카운트 (가스라이팅 방지)
--   • documents.view_count(누적값)는 그대로 유지해 문서 상세 응답의 누적 조회수 표시에 계속 사용
--
-- 노션은 위 정책에 맞춰 갱신 예정. 향후 추가 정책(세션/IP 기반 dedup, 클릭과 조회 분리)이 결정되면
-- 이 테이블 스키마에 컬럼을 더하거나 별도 테이블을 도입해 확장한다.
CREATE TABLE document_views (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    viewed_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_document_views_document
        FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    CONSTRAINT fk_document_views_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 인기 문서 7일 윈도우 집계용 — (document_id, viewed_at) 복합 인덱스.
-- 쿼리 패턴: WHERE viewed_at >= :since GROUP BY document_id.
CREATE INDEX idx_document_views_document_viewed_at ON document_views (document_id, viewed_at);

-- 사용자별 활동 추적·중복 진단용 (향후 사용자 행동 통계 확장에 활용).
CREATE INDEX idx_document_views_user_viewed_at ON document_views (user_id, viewed_at);
